### ISSUE TITLE
Please update to AStyle 3.1

### ISSUE THREAD

**Issue by pingel** [lukamicoder/astyle-extension#11]
Would be nice if the dll was updated to 3.1

Also, unknown options should simply be silently ignored (or option to do so) and also option to spawn astyle.exe instead of bundled astyle.dll so the user can stay on the latest astyle without waiting for a new plugin.

**Comment by pingel** [comment]
Perhaps at least allow "--options=<filename>"

**Comment by M1ghty1** [comment]
I would appreciate an update to 3.1 too :-D

**Comment by lukamicoder** [comment]
You can manually update the bundled astyle.dll if needed. In any case, Artistic Style 3.1 is now supported.

**Comment by M1ghty1** [comment]
Great, thanks for the update :-)
In the marketplace for VS Extensions i still can't find the new version:
https://marketplace.visualstudio.com/items?itemName=Lukamicoder.AStyleExtension2017

Is there something missing?
