### ISSUE TITLE
support vs2019 please ..

### ISSUE THREAD

**Issue by ivanleo** [lukamicoder/astyle-extension#16]
I like thie extension so much
and my teamer also like it
so support vs2019 please

**Comment by lukamicoder** [comment]
Visual Studio 2019 is now supported.

**Comment by duyaokun** [comment]
When will we  find it in [marketplace](https://marketplace.visualstudio.com/search?term=astyle&target=VS&category=Tools&vsVersion=&subCategory=All&sortBy=Relevance)

**Comment by igitur** [comment]
@lukamicoder 

Visual Studio 2019 doesn't detect this extension, because the market place doesn't say it's supported.

![image](https://user-images.githubusercontent.com/145854/64785156-0646d380-d56c-11e9-80c5-75f4cadd5dc7.png)

**Comment by migurazi** [comment]
I downloaded the source from github, built it on VS 2019(Community), and installed it on VS 2019.

https://github.com/lukamicoder/astyle-extension

**Comment by Loggi-pro** [comment]
> I downloaded the source from github, built it on VS 2019(Community), and installed it on VS 2019.
> 
> https://github.com/lukamicoder/astyle-extension

How did you do that? When i changed Install target range in manifest to supply 17.0 - vsix installer still not finded vs2019 on pc.

**Comment by piyushsoni** [comment]
@migurazi : Would you be able to share the built vs 2019 extension? Some of us are technologically a little less skilled. :) Thanks!

**Comment by sychev** [comment]
> @migurazi : Would you be able to share the built vs 2019 extension? Some of us are technologically a little less skilled. :) Thanks!

Here is the build for the Visual Studio 2019
https://github.com/lukamicoder/astyle-extension/issues/17#issuecomment-537814439
