### ISSUE TITLE
CheckBox --intend-preproc-block without function

### ISSUE THREAD

**Issue by Cpt-Kork** [lukamicoder/astyle-extension#4]
In AStyle Settings dialog for C/C++ the check box for the "--intend-preproc-block" parameter is not bound to any functionality. Similarly, setting the parameter through the Edit command line option gets lost once the Settings dialog is opened.
Thx for fixing it!

**Comment by lukamicoder** [comment]
Thank you for reporting it. Version 2.7 has been released with a fix.
