### ISSUE TITLE
Have a plan of supports visual studio 2017?

### ISSUE THREAD

**Issue by duyaokun** [lukamicoder/astyle-extension#8]
Visual studio 2017 is released, have a plan of supports visual studio 2017?

**Comment by lukamicoder** [comment]
The Visual Studio 2017 version is available at [AStyleExtension2017](https://marketplace.visualstudio.com/items?itemName=Lukamicoder.AStyleExtension2017l)

**Comment by duyaokun** [comment]
thank you very much!

**Comment by lukamicoder** [comment]
It is already supported:
https://marketplace.visualstudio.com/items?itemName=Lukamicoder.AStyleExtension2017
